# Generated by Django 4.1.5 on 2023-01-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_subject_quiz_question_option"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={"verbose_name": "Option", "verbose_name_plural": "Options"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "ordering": ("-authored_on",),
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ("name",),
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="quiz",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
